spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/commerce_delivery
    username: frosty
    password: ytsorf
    driver-class-name: org.postgresql.Driver
  cache:
    type: caffeine
    cache-names:
      - delivery.deliveries
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60m

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings, httptrace, caches, threaddump

resilience4j.circuitbreaker:
  instances:
    warehouseCircuitBreaker:
      slidingWindowSize: 50
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    root: INFO
    ru.yandex.practicum.delivery: TRACE
    ru.yandex.practicum.interaction.api.logging: TRACE