spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/commerce_order
    username: frosty
    password: ytsorf
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine
    cache-names:
      - order.orders
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60m

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings, httptrace, caches, threaddump

resilience4j.circuitbreaker:
  instances:
    warehouseCircuitBreaker:
      slidingWindowSize: 50
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    root: INFO
    ru.yandex.practicum.order: TRACE
    ru.yandex.practicum.interaction.api.logging: TRACE